#!/bin/bash

set -xe

quicktype figma.ts -o swift/Figma.swift --access-level public
quicktype figma.ts -o swift-alamofire/Figma.swift --alamofire --access-level public
quicktype figma.ts -o csharp/Figma.cs
quicktype figma.ts -o go/figma.go
quicktype figma.ts -o rust/figma.rs
quicktype figma.ts -o cpp/figma.cpp
quicktype figma.ts -o objective-c/FGFigma.m --class-prefix FG

rm java/*.java
quicktype figma.ts -o java/Figma.java

quicktype figma.ts -o typescript/figma.ts
quicktype figma.ts -o javascript/figma.js
quicktype figma.ts -l flow -o flow/figma.js
quicktype figma.ts -o elm/figma.elm